/**
 * Created by liwei on 15/5/6.
 */
seajs.config({
    // base: 'http://source.ycode.cn/officalSite/js/',
    alias: {
        'romeDate': '/static/js/activity/rome.js?v=1',
        'raty': '/static/js/jquery.raty.js?v=1',
        'jquery': 'modules/core/0.1.0/jquery-2.1.1.min.js?v=1',
        'jqueryy': 'modules/core/0.1.0/jquery-1.9.1.min.js?v=1',
        'jedate': 'modules/core/0.1.0/jedate.js?v=1',
        'doT': 'modules/core/0.1.0/doT.min.js?v=1',
        'easing': 'modules/core/0.1.0/jquery.easing.min.js?v=1',
        // 'echarts':'http://echarts.baidu.com/build/dist/echarts-all.js',
        'echarts': '/static/plugins/echarts/echarts-all.js',
        /**！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
         * echarts 2.0与3.0存在部分接口和写法的不同
         * ！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
         * */
        'echarts3': '//cdnjs.cloudflare.com/ajax/libs/echarts/3.3.1/echarts.js',
        'echarts4': 'modules/core/0.1.0/echarts.min.js',
        'Rome': 'modules/core/0.1.0/rome.js',
        'vue': 'modules/core/0.1.0/vue.min.js',

        'paginator': 'modules/core/0.1.0/bootstrap/js/bootstrap-paginator.min.js?v=1',
        'ajaxfileupload': 'modules/core/0.1.0/ajaxfileupload.js?v=1',
        'widget': 'modules/core/0.1.0/jquery-upload/vendor/jquery.ui.widget.js?v=1',
        'transport': 'modules/core/0.1.0/jquery-upload/jquery.iframe-transport.js?v=1',
        'fileupload': 'modules/core/0.1.0/jquery-upload/jquery.fileupload.js?v=1',
        'experienceScore': 'modules/core/0.1.0/experienceScore.js?v=1',
        'fancybox': 'modules/core/0.1.0/fancyBox/jquery.fancybox.js?v=1',
        'fancybox_seajs': 'modules/core/0.1.0/fancyBox/fancybox_seajs.js?v=1',
        'common': 'modules/core/0.1.0/common.js?v=1',
        'imgZoom': 'modules/imgZoom/0.1.0/jquery.artZoom4Liaoba.js?v=2',
        'cal': 'modules/calendar/0.1.0/WdatePicker.js?v=1',
        'chengji': 'modules/chengji/0.1.0/chengji.js?v=1',
        'schoolsecurity': 'modules/schoolsecurity/0.1.0/schoolsecurity.js?v=1',
        'itempool': 'modules/itempool/0.1.0/itempool.js?v=1',
        'department': 'modules/department/0.1.0/department.js?v=1',
        'moralculturemanage': 'modules/moralculture/0.1.0/moralculturemanage.js?v=1',
        'teachermoralculture': 'modules/moralculture/0.1.0/teachermoralculture.js?v=1',
        'studentmoralculture': 'modules/moralculture/0.1.0/studentmoralculture.js?v=1',
        'studentmoralculturescore': 'modules/moralculture/0.1.0/studentmoralculturescore.js',
        'teacherClass': 'modules/myclass/0.1.0/teacherClass.js?v=1',
        'classManage1': 'modules/myclass/0.1.0/classManage.js?v=1',
        'ajaxForm': 'modules/core/0.1.0/jquery-upload/jquery.form.min.js',
        'attendance': 'modules/myclass/0.1.0/attendance.js?v=1',
        'depFile': 'modules/myschool/0.1.0/departmentFile.js?v=1',
        'jiangcheng': 'modules/jiangcheng/0.1.0/jiangcheng.js?v=1',
        'salaryItem': 'modules/salary/0.1.0/salaryItem.js?v=1',
        'bxgl': 'modules/bxgl/0.1.0/bxgl.js?v=1',
        'dialog': 'modules/dialog/0.1.0/jquery-ui.min.js?v=1',
        'treeview': 'modules/treeView/0.2.0/jquery.ztree.all-3.5.min.js?v=1',
        'qcdj': 'modules/qcdj/0.1.0/qcdj.js?v=1',
        'xcdj': 'modules/xcdj/0.1.0/xcdj.js?v=1',
        'salary': 'modules/salary/0.1.0/salary.js?v=1',
        'kwgl': 'modules/kwgl/0.1.0/kwgl.js?v=1',
        'homepage': "modules/homepage/0.1.0/homepage.js?v=1",
        'activityMain': 'modules/friendcircle/0.1.0/activityMain.js?v=1',
        'friendList': 'modules/friendcircle/0.1.0/friendList.js?v=1',
        'friendSearch': 'modules/friendcircle/0.1.0/friendSearch.js?v=1',
        'friendMessage': 'modules/friendcircle/0.1.0/friendMessage.js?v=1',
        'friendReplyMsg': 'modules/friendcircle/0.1.0/friendReplyMsg.js?v=1',
        'role': 'modules/friendcircle/0.1.0/role.js?v=1',
        'initPaginator': 'modules/friendcircle/0.1.0/initPaginator.js?v=1',
        'leftBar': 'modules/friendcircle/0.1.0/leftBar.js?v=1',
        'rome': 'modules/friendcircle/0.1.0/rome.js?v=1',
        'activityView': 'modules/friendcircle/0.1.0/activityView.js?v=1',
        'studentScore': 'modules/interestclass/0.1.0/studentScore.js?v=1',
        'content_zoom': 'modules/interestclass/0.1.0/content_zoom.js?v=1',
        'curricula': 'modules/myclass/0.1.0/curricula.js?v=1',
        'curriculaI': 'modules/myschool/0.1.0/curriculaI.js?v=2',
        'pagination': 'modules/pagination/0.1.0/jqPaginator.min.js?v=1',
        'competition': 'modules/competition/0.1.0/competition.js?v=1',
        'viewSalary': 'modules/salary/0.1.0/viewSalary.js?v=1',
        'documentCreate': 'modules/docflow/0.1.0/documentCreate.js?v=1',
        'documentCreateEdu': 'modules/docflow/0.1.0/documentCreateEdu.js?v=1',
        'documentList': 'modules/docflow/0.1.0/documentList.js?v=1',
        'documentListEdu': 'modules/docflow/0.1.0/documentListEdu.js?v=1',
        'documentDetail': 'modules/docflow/0.1.0/documentDetail.js?v=1',
        'documentDetailEdu': 'modules/docflow/0.1.0/documentDetailEdu.js?v=1',
        'documentCheck': 'modules/docflow/0.1.0/documentCheck.js?v=1',
        'documentModify': 'modules/docflow/0.1.0/documentModify.js?v=1',
        'documentModifyEdu': 'modules/docflow/0.1.0/documentModifyEdu.js?v=1',
        'myDocumentModify': 'modules/docflow/0.1.0/myDocumentModify.js?v=1',
        'microlesson': 'modules/microlesson/0.1.0/microlesson.js?v=1',
        'micromatch': 'modules/microlesson/0.1.0/micromatch.js?v=1',
        'matchdetail': 'modules/microlesson/0.1.0/matchdetail.js?v=1',
        'lessondetail': 'modules/microlesson/0.1.0/lessondetail.js?v=1',
        'interactlesson': 'modules/interactlesson/0.1.0/interactlesson.js?v=1',
        'matchresult': 'modules/microlesson/0.1.0/matchresult.js?v=1',
        'editmatch': 'modules/microlesson/0.1.0/editmatch.js?v=1',
        'educationSchools': '/static_new/js/modules/managecount/0.1.0/educationSchools.js?v=1',
        'totalpage': '/static_new/js/modules/managecount/0.1.0/totalpage.js?v=1',
        'teachertotalpage': '/static_new/js/modules/managecount/0.1.0/teachertotalpage.js?v=1',
        'funUseCount': '/static_new/js/modules/managecount/0.1.0/funUseCount.js?v=1',
        'teacherFunUseCount': '/static_new/js/modules/managecount/0.1.0/teacherFunUseCount.js?v=1',
        'funUseDetail': '/static_new/js/modules/managecount/0.1.0/funUseDetail.js?v=1',
        'manageCountUtils': '/static_new/js/modules/managecount/0.1.0/manageCountUtils.js?v=1',
        'roll': 'modules/roll/0.1.0/roll.js?v=1',
        'rewardHistory': 'modules/roll/0.1.0/rewardHistory.js?v=1',
        'addresource': 'modules/ziyuanguanli/0.1.0/addresource.js?v=1',
        'gitresource': 'modules/ziyuanguanli/0.1.0/gitresource.js?v=1',
        'family': 'modules/family/0.1.0/family.js?v=1',
        'ziyuanguanli': 'modules/ziyuanguanli/0.1.0/ziyuanguanli.js?v=1',
        'addziyuan': 'modules/ziyuanguanli/0.1.0/addziyuan.js?v=1',
        'ziyuanGit': 'modules/ziyuanguanli/0.1.0/ziyuanGit.js?v=1',
        'addtiku': 'modules/tiku/0.1.0/addtiku.js?v=1',
        'webuploader': 'modules/webuploader/webuploader.min.js',
        'imguploader': 'modules/webuploader/imgUpload.js?v=1',
        'fileuploader': 'modules/webuploader/fileUpload.js?v=1',
        'videoUploadTwo': 'modules/webuploader/videoUploadTwo.js?v=1',
        'fileUploadTwo': 'modules/webuploader/fileUploadTwo.js?v=1',
        'addToGit': 'modules/ziyuanguanli/0.1.0/addToGit.js?v=1',
        'gitresourseedit': 'modules/ziyuanguanli/0.1.0/gitresourseedit.js?v=1',
        'editZiyuan': 'modules/ziyuanguanli/0.1.0/editZiyuan.js?v=1',
        'tikulist': 'modules/tiku/0.1.0/tikulist.js?v=1',
        'editTiku': 'modules/tiku/0.1.0/editTiku.js?v=1',
        'areaExam': 'modules/areaExam/0.1.0/areaExam.js?v=1',
        'educationAreaExam': 'modules/areaExam/0.1.0/educationAreaExam.js?v=1',
        'newRegional': 'modules/regionalExam/0.1.0/newRegional.js?v=1',
        'inputGrade': 'modules/areaExam/0.1.0/inputGrade.js?v=1',
        'rankingList': 'modules/exam/0.1.0/rankingList.js?v=1',
        'chakan': 'modules/exam/0.1.0/chakan.js?v=1',
        'studentlist': 'modules/exam/0.1.0/studentlist.js?v=1',
        'headmastereclass': 'modules/lanclass/0.1.0/headmastereclass.js?v=1',
        'lanclass': 'modules/lanclass/0.1.0/lanclass.js?v=1',
        'lessonclass': 'modules/lanclass/0.1.0/lessonclass.js?v=1',
        'vote': 'modules/vote/0.1.0/vote.js?v=1',
        'uploadify': 'modules/core/0.1.0/jquery.uploadify.min.js',
        'sharedpart': 'modules/core/0.1.0/sharedpart.js',
        'eduManageList': 'modules/educationbureau/0.1.0/eduManageList.js?v=1',
        'addEducation': 'modules/educationbureau/0.1.0/addEducation.js?v=1',
        'editEducation': 'modules/educationbureau/0.1.0/editEducation.js?v=1',
        'dorm': 'modules/dorm/0.1.0/dorm.js?v=1',
        'dormList': 'modules/dorm/0.1.0/dormList.js',
        'studentIn': 'modules/dorm/0.1.0/studentIn.js?v=1',
        'classManage': 'modules/funclassroom/0.1.0/classManage.js',
        'classAppoint': 'modules/funclassroom/0.1.0/classAppoint.js',
        'myManage': 'modules/funclassroom/0.1.0/myManage.js',
        'myAppointment': 'modules/funclassroom/0.1.0/myAppointment.js',
        'enterSchool': 'modules/guard/0.1.0/enterSchool.js?v=1',
        'outSchool': 'modules/guard/0.1.0/outSchool.js?v=1',
        'visiting': 'modules/guard/0.1.0/visiting.js?v=1',
        'ecart': 'modules/mall/0.1.0/ecart.js?v=1',
        'eaddress': 'modules/mall/0.1.0/eaddress.js?v=1',
        'orderpage': 'modules/mall/0.1.0/orderpage.js?v=1',
        'yunying': "modules/yunying/0.1.0/yunying.js?v=1",
        'letter': "modules/yunying/0.1.0/letter.js?v=1",
        'replyletter': "modules/yunying/0.1.0/replyletter.js?v=1",
        'schedule': "modules/schedule/0.1.0/schedule.js?v=1",
        'importSchedule': "modules/schedule/0.1.0/importSchedule.js?v=1",
        'teacherLeave': "modules/teacherLeave/0.1.0/teacherLeave.js?v=1",
        'manageLeave': "modules/teacherLeave/0.1.0/manageLeave.js?v=1",
        'furtheredu': "modules/teachermanage/0.1.0/furtheredu.js?v=1",
        'userBasic': "modules/user/0.1.0/userBasic.js?v=1",
        'projectManage': "modules/quality/0.1.0/projectManage.js?v=1",
        'growthRecord': "modules/growRecord/0.1.0/growthRecord.js?v=1",
        'growthDetail': "modules/growRecord/0.1.0/growthDetail.js?v=1",
        'indicator': "modules/indicator/0.1.0/indicator.js",
        'evaluate': "modules/indicator/0.1.0/evaluate.js",
        'indicatorTree': "modules/indicator/0.1.0/indicatorTree.js",
        'evaluateManage': "modules/indicator/0.1.0/evaluateManage.js",
        'evaluateTimes': "modules/indicator/0.1.0/evaluateTimesMge.js",
        'evaluateResult': "modules/indicator/0.1.0/evaluateResult.js",
        'evaluateTimesResult': "modules/indicator/0.1.0/evaluateTimesResult.js",
        'evaluateRInfo': "modules/indicator/0.1.0/evaluateResultInfo.js",
        'stuEvaluateDetail': "modules/indicator/0.1.0/stuEvaluateDetail.js",
        'addProject': "modules/quality/0.1.0/addProject.js?v=1",
        'edubxgl': "modules/bxgl/0.1.0/edubxgl.js?v=1",
        'expressTemplate': "modules/mall/0.1.0/admin/expressTemplate.js?v=1",
        'express': "modules/mall/0.1.0/express.js?v=1",
        'countMain': '/static_new/js/modules/managecount/0.1.0/countMain.js?v=1',
        'orderDetail': "modules/mall/0.1.0/orderdetail.js?v=1",
        'uploadVideo': 'modules/mall/0.1.0/admin/uploadVideo.js?v=1',
        'userAccount': "modules/user/0.1.0/userAccount.js?v=1",
        'select2': "modules/select2/select2.min.js?v=1",
        'collection': 'modules/mall/0.1.0/collection.js?v=1',
        'history': 'modules/mall/0.1.0/history.js?v=1',
        'user': 'modules/mall/0.1.0/user.js?v=1',
        'addressManage': 'modules/mall/0.1.0/addressManage.js?v=1',
        'birthday': 'modules/birthday/birthday.js?v=1',
        'goodsManage': 'modules/mall/0.1.0/admin/goodsManage.js?v=1',
        'zoubanAttendance': 'modules/zouban/0.1.0/attendance/attendance.js?v=1',
        'nolesson': 'modules/zouban/0.1.0/student/nolesson.js?v=1',
        'cloudresource': 'modules/cloudresource/0.1.0/cloudresource.js?v=1',
        'lessonpublished': 'modules/zouban/0.1.0/student/lessonpublished.js?v=1',
        'lessonselect': 'modules/zouban/0.1.0/student/lessonselect.js?v=1',
        'interestlessonselect': 'modules/zouban/0.1.0/student/interestlessonselect.js?v=1',
        'clashcheck': 'modules/zouban/0.1.0/admin/clashcheck.js?v=1',
        'checklist': 'modules/zouban/0.1.0/admin/checklist.js?v=1',
        'arranging': 'modules/zouban/0.1.0/admin/arranging.js?v=1',
        'bianban': 'modules/zouban/0.1.0/manage/bianban.js?v=1',
        'lessoninstall': 'modules/zouban/0.1.0/manage/lessoninstall.js?v=1',
        'zoubanindex': 'modules/zouban/0.1.0/zoubanindex.js?v=1',
        'gezhiindex': 'modules/zouban/0.1.0/gezhiindex.js?v=1',
        'zhuzhouindex': 'modules/zouban/0.1.0/zhuzhouindex.js?v=1',
        'changZhengIndex': 'modules/zouban/0.1.0/changZhengIndex.js?v=1',
        'chooselesson': 'modules/zouban/0.1.0/manage/chooselesson.js?v=1',
        'interestChooselesson': 'modules/zouban/0.1.0/manage/interestChooselesson.js?v=1',
        'classrule': 'modules/zouban/0.1.0/manage/classrule.js?v=1',
        'gezhiClassrule': 'modules/zouban/0.1.0/manage/gezhiClassrule.js?v=1',
        'zhuzhouTeacher': 'modules/zouban/0.1.0/manage/zhuzhouTeacher.js?v=1',
        'publishcourse': 'modules/zouban/0.1.0/admin/publishcourse.js?v=1',
        'chargeteacher': 'modules/zouban/0.1.0/charge-teacher/charge-teacher.js?v=1',
        'teacher': 'modules/zouban/0.1.0/charge-teacher/teacher.js?v=1',
        'zhuzhou-teacher': 'modules/zouban/0.1.0/charge-teacher/zhuzhou-teacher.js?v=1',
        'courseteacher': 'modules/zouban/0.1.0/teacher/course-teacher.js?v=1',
        'zhuzhou-course-teacher': 'modules/zouban/0.1.0/teacher/zhuzhou-course-teacher.js?v=1',
        'migrate': 'modules/zouban/0.1.0/jquery-migrate-1.1.0.js',
        'adjust': 'modules/zouban/0.1.0/admin/adjust.js?v=1',
        'adjustV2': 'modules/zouban/0.1.0/admin/adjustV2.js?v=1',
        'classList': 'modules/zouban/0.1.0/attendance/classlist.js?v=1',
        'lesson': 'modules/zouban/0.1.0/attendance/lesson.js?v=1',
        'xunshiScore': 'modules/zouban/0.1.0/attendance/xunshiscore.js?v=1',
        'bianbanrule': 'modules/zouban/0.1.0/manage/bianbanrule.js?v=1',
        'zoubanIndex': 'modules/zouban/2.0/index.js?v=1',
        'zoubanModeConfig': 'modules/zouban/2.0/modeConfig.js?v=1',
        'zoubanFenban': 'modules/zouban/2.0/fenban.js?v=1',
        'paike': 'modules/zouban/2.0/paike.js?v=1',
        'layer': 'modules/core/0.1.0/layer/layer.js?v=1',
        'tiaoke': 'modules/zouban/2.0/tiaoke.js?v=1',
        'microSchool': 'modules/learncenter/0.2.0/microSchool.js?v=2',
        'microCount': 'modules/learncenter/0.2.0/microCount.js?v=2',
        'microAll': 'modules/learncenter/0.2.0/microAll.js?v=2',
        'microPT': 'modules/learncenter/0.3.0/microPT.js?v=2',
        'microXB': 'modules/learncenter/0.3.0/microXB.js?v=2',
        'microDetails': 'modules/learncenter/0.3.0/microDetails.js?v=2',
        'microXQ': 'modules/learncenter/0.3.0/microXQ.js?v=2',
        'goodsManage': 'modules/mall/0.1.0/admin/goodsManage.js?v=1',
        'gzxmgl': 'modules/gzgl/0.1.0/gzxmgl.js?v=1',
        'wdgz': 'modules/gzgl/0.1.0/wdgz.js?v=1',
        'gztj': 'modules/gzgl/0.1.0/gztj.js?v=1',
        'mykaoqin': 'modules/smartcard/0.1.0/mykaoqin.js?v=1',
        'stukaoqin': 'modules/smartcard/0.1.0/stukaoqin.js?v=1',
        'teakaoqin': 'modules/smartcard/0.1.0/teakaoqin.js?v=1',
        'gradekaoqin': 'modules/smartcard/0.1.0/gradekaoqin.js?v=1',
        'classkaoqin': 'modules/smartcard/0.1.0/classkaoqin.js?v=1',
        'classstukaoqin': 'modules/smartcard/0.1.0/classstukaoqin.js?v=1',
        'stukaoqindetail': 'modules/smartcard/0.1.0/stukaoqindetail.js?v=1',
        'userdoor': 'modules/smartcard/0.1.0/userdoor.js?v=1',
        'weikeziyuanguanli': 'modules/weikeziyuanguanli/0.1.0/weikeziyuanguanli.js?v=1',
        'addWeiKeToGit': 'modules/weikeziyuanguanli/0.1.0/addWeiKeToGit.js?v=1',
        'weikeziyuangit': 'modules/weikeziyuanguanli/0.1.0/weikeziyuangit.js?v=1',
        'addWeiKe': 'modules/weikeziyuanguanli/0.1.0/addWeiKe.js?v=1',
        'itempoolMge': 'modules/itempoolguanli/0.1.0/itempoolMge.js?v=1',
        'addItem': 'modules/itempoolguanli/0.1.0/addItem.js?v=1',
        'editItem': 'modules/itempoolguanli/0.1.0/editItem.js?v=1',
        'lessonWareMge': 'modules/kejianziyuanguanli/0.1.0/lessonWareMge.js?v=1',
        'addLessonWareToGit': 'modules/kejianziyuanguanli/0.1.0/addLessonWareToGit.js?v=1',
        'lessonWareGit': 'modules/kejianziyuanguanli/0.1.0/lessonWareGit.js?v=1',
        'addLessonWare': 'modules/kejianziyuanguanli/0.1.0/addLessonWare.js?v=1',
        'population': 'modules/peoplegroup/0.1.0/peoplegroup.js?v=1',
        'dorm': 'modules/peoplegroup/0.1.0/dorm.js?v=1',
        'consume': 'modules/peoplegroup/0.1.0/consume.js?v=1',
        'track': 'modules/peoplegroup/0.1.0/track.js?v=1',
        'zhiban': 'modules/zhiban/0.1.0/zhiban.js?v=1',
        'jiaban': 'modules/jiaban/0.1.0/jiaban.js?v=1',
        'myjiaban': 'modules/jiaban/0.1.0/myjiaban.js?v=1',
        'meet': 'modules/meeting/0.1.0/hyandhd.js?v=1',
        'meetxq': 'modules/meeting/0.1.0/meetxq.js?v=1',
        'listnav': 'modules/core/0.1.0/jquery.listnav.min-2.1.js?v=1',
        'charfist': 'modules/core/0.1.0/jquery.charfirst.pinyin.js?v=1',
        /*'zTree':'modules/zTree/js/jquery.ztree.all-3.5.js?v=1',
         'zTreeCore':'modules/zTree/js/jquery.ztree.core-3.5.js?v=1',
         'zTreeExedit':'modules/zTree/js/jquery.ztree.exedit-3.5.js?v=1',
         'zTreeExcheck':'modules/zTree/js/jquery.ztree.excheck-3.5.js?v=1',*/
        'zTree': 'modules/zTree/js/jquery.ztree.core.min.js?v=1',
        'zTreeCore': 'modules/zTree/js/jquery.ztree.core.js?v=1',
        'zTreeExcheck': 'modules/zTree/js/jquery.ztree.excheck.js?v=1',
        'zTreeExedit': 'modules/zTree/js/jquery.ztree.exedit.js?v=1',
        'drag': 'modules/zouban/2.0/drag.js?v=1',
        'notice': 'modules/notice/0.1.0/notice.js?v=1',
        'folder': 'modules/folder/0.1.0/folder.js?v=1',
        'folder2': 'modules/folder/0.1.0/folder2.js?v=1',
        'edumange': 'modules/schoolbase/0.1.0/edumange.js?v=1',
        'orgchart': 'modules/schoolbase/jquery.orgchart.js?v=1',
        'teamange': 'modules/schoolbase/0.1.0/teamange.js?v=1',
        'grademange': 'modules/schoolbase/0.1.0/grademange.js?v=1',
        'subjectmange': 'modules/schoolbase/0.1.0/subjectmange.js?v=1',
        'classmange': 'modules/schoolbase/0.1.0/classmange.js?v=1',
        'studentmange': 'modules/schoolbase/0.1.0/studentmange.js?v=1',
        'termmange': 'modules/schoolbase/0.1.0/termmange.js?v=1',
        'timetablemange': 'modules/schoolbase/0.1.0/timetablemange.js?v=1',
        'schoolUserInfo': 'modules/schoolbase/0.1.0/schoolUserInfo.js?v=1',
        'page': 'modules/schoolbase/0.1.0/jquery.page.js?v=1',
        'viewer': '/static_new/js/modules/core/0.1.0/viewer.min.js',
        'kpiManage': '/static_new/js/modules/indicator/0.1.0/kpiManage.js?v=1',
        'grabClass': 'modules/extensionClass/0.1.0/grabClass.js?v=1',
        'teaRanEvaluate': 'modules/extensionClass/0.1.0/teaRanEvaluate.js?v=1',
        'teaEvaluate': 'modules/extensionClass/0.1.0/teaEvaluate.js',
        'Raty': 'modules/extensionClass/0.1.0/raty.js?v=1',
        'myExtension': 'modules/extensionClass/0.1.0/myExtension.js?v=1',
        'teaExtension': 'modules/extensionClass/0.1.0/teaExtension.js?v=1',
        'studentCourse': 'modules/extensionClass/0.1.0/studentCourse.js?v=1',
        'extensionSetting': 'modules/extensionClass/0.1.0/extensionSetting.js?v=1',
        'stuManage': 'modules/extensionClass/0.1.0/stuManage.js?v=1',
        'attendance': 'modules/extensionClass/0.1.0/attendance.js?v=1',
        'groupType': 'modules/group/0.1.0/groupType.js?v=1',
        'grouppage': 'modules/group/0.1.0/grouppage.js?v=1',
        'result': 'modules/versionquestionnaire/result.js?v=1',
        'newQuest': 'modules/versionquestionnaire/newQuest.js?v=1',
        'questList': 'modules/versionquestionnaire/questList.js?v=1',
        'questIndex': 'modules/versionquestionnaire/questIndex.js?v=1',
        'questDetail': 'modules/versionquestionnaire/questDetail.js?v=1',
        'questInfo': 'modules/versionquestionnaire/questInfo.js?v=1',
        'onlinePractice': 'modules/onlinePractice/0.1.0/onlinePractice.js?v=1',
        'practiceRecord': 'modules/onlinePractice/0.1.0/practiceRecord.js?v=1',
        'rewardQuestion': 'modules/onlinePractice/0.1.0/rewardQuestion.js?v=1',
        'rewardPublish': 'modules/onlinePractice/0.1.0/rewardPublish.js?v=1',
        'errorBook': "modules/onlinePractice/0.1.0/errorBook.js?v=1",
        'rewardAnswer': 'modules/onlinePractice/0.1.0/rewardAnswer.js?v=1',
        'checkModel': 'modules/checkRating/0.1.0/checkModel.js?v=1',
        'checkSet': 'modules/checkRating/0.1.0/checkSet.js?v=1',
        'checkInp': 'modules/checkRating/0.1.0/checkInp.js?v=1',
        'checkInphv': 'modules/checkRating/0.1.0/checkInphv.js?v=1',
        'microSet': 'modules/learncenter/0.2.0/microSet.js?v=2',
        'teaExtension': 'modules/extensionClass/0.1.0/teaExtension.js?v=1',
        'extensionSetting': 'modules/extensionClass/0.1.0/extensionSetting.js?v=1',
        'stuManage': 'modules/extensionClass/0.1.0/stuManage.js?v=1',
        'attendance': 'modules/extensionClass/0.1.0/attendance.js?v=1',
        'groupType': 'modules/group/0.1.0/groupType.js?v=1',
        'grouppage': 'modules/group/0.1.0/grouppage.js?v=1',
        'result': 'modules/versionquestionnaire/result.js?v=1',
        'newQuest': 'modules/versionquestionnaire/newQuest.js?v=1',
        'questList': 'modules/versionquestionnaire/questList.js?v=1',
        'questIndex': 'modules/versionquestionnaire/questIndex.js?v=1',
        'questDetail': 'modules/versionquestionnaire/questDetail.js?v=1',
        'questInfo': 'modules/versionquestionnaire/questInfo.js?v=1',
        'onlinePractice': 'modules/onlinePractice/0.1.0/onlinePractice.js?v=1',
        'practiceRecord': 'modules/onlinePractice/0.1.0/practiceRecord.js?v=1',
        'rewardQuestion': 'modules/onlinePractice/0.1.0/rewardQuestion.js?v=1',
        'rewardPublish': 'modules/onlinePractice/0.1.0/rewardPublish.js?v=1',
        'errorBook': "modules/onlinePractice/0.1.0/errorBook.js?v=1",
        'rewardAnswer': 'modules/onlinePractice/0.1.0/rewardAnswer.js?v=1',
        'checkModel': 'modules/checkRating/0.1.0/checkModel.js?v=1',
        'checkSet': 'modules/checkRating/0.1.0/checkSet.js?v=1',
        'checkInp': 'modules/checkRating/0.1.0/checkInp.js?v=1',
        'checkInphv': 'modules/checkRating/0.1.0/checkInphv.js?v=1',
        'microSet': 'modules/learncenter/0.2.0/microSet.js?v=2',
        'mycollect': 'modules/learncenter/0.2.0/mycollect.js?v=2',
        'myMicro': 'modules/learncenter/0.2.0/myMicro.js?v=2',
        'mycollects': 'modules/learncenter/0.2.0/mycollects.js?v=2',
        'page': 'modules/schoolbase/0.1.0/jquery.page.js?v=1',
        'cloudLesson': 'modules/learncenter/0.2.0/cloudLesson.js?v=2',
        'microDetail': 'modules/learncenter/0.2.0/microDetail.js?v=2',
        'attendanceSet': 'modules/attendance/attendanceSet.js?v=2',
        'attendanceCount': 'modules/attendance/attendanceCount.js?v=2',
        'attendanceRecord': 'modules/attendance/attendanceRecord.js?v=2',
        'attendanceleave': 'modules/attendance/attendanceleave.js?v=2',
        'attendanceKao': 'modules/attendance/attendanceKao.js?v=2',
        'evaluation': 'modules/evaluation/0.1.0/evaluation.js?v=1',
        'geEvaluation': 'modules/evaluation/0.1.0/geEvaluation.js?v=1',
        'geEvaluation2': 'modules/evaluation/0.1.0/geEvaluation2.js?v=1',
        'empirical': 'modules/evaluation/0.1.0/empirical.js?v=1',
        'administration': 'modules/evaluation/0.1.0/administration.js?v=1',
        'AttendanceSet': 'modules/askleave/AttendanceSet.js?v=1',
        'myLeave': 'modules/askleave/myLeave.js?v=1',
        'leave': 'modules/askleave/leave.js?v=1',
        'count': 'modules/askleave/count.js?v=1',
        'evaluation': 'modules/evaluation/0.1.0/evaluation.js?v=1',
        'paperCreate': 'modules/itempool/0.2.0/paperCreate.js?v=1',
        'paperSelect': 'modules/itempool/0.2.0/paperSelect.js?v=1',
        'paperSelect1': 'modules/itempool/0.2.0/paperSelect1.js?v=1',
        'testpaper': 'modules/itempool/0.2.0/testpaper.js?v=1',
        'testpaperSubject': 'modules/itempool/0.2.0/testpaperSubject.js?v=1',
        'paperDetail': 'modules/itempool/0.2.0/paperDetail.js?v=1',
        'appManage': 'modules/appManage/0.1.0/appManage.js?v=1',
        'scrollHighlight': 'modules/appManage/0.1.0/scrollHighlight.js?v=1',
        'nroll': 'modules/appManage/0.1.0/nroll.js?v=1',
        'newVote': 'modules/vote/0.2.0/vote.js?v=1',
        'nianji': 'modules/analysis/1.0.1/nianji.js?v=1',
        'myscore': 'modules/analysis/1.0.1/myscore.js?v=1',
        'totals': 'modules/analysis/1.0.1/totals.js?v=1',
        'stuscore': 'modules/analysis/1.0.1/stuscore.js?v=1',
        'score': 'modules/analysis/1.0.1/score.js?v=1',
        'trend': 'modules/analysis/1.0.1/trend.js?v=1',
        'heads': 'modules/analysis/1.0.1/heads.js?v=1',
        'jste': 'modules/analysis/1.0.1/jste.js?v=1',
        'examination': 'modules/jinyuanananly/examination.js?v=1',
        'examinationadd': 'modules/jinyuanananly/examinationadd.js?v=1',
        'examinationaddI': 'modules/jinyuanananly/examinationaddI.js?v=1',
        'televels': 'modules/analysis/1.0.1/televels.js?v=1',
        'lscore': 'modules/analysis/1.0.1/lscore.js?v=1',
        'inputscore': 'modules/analysis/1.0.1/inputscore.js?v=1',
        'publisher': 'modules/version/0.1.0/publisher.js?v=1',
        'chapterDirectory': 'modules/version/0.1.0/chapterDirectory.js?v=1',
        'chapterDetail': 'modules/version/0.1.0/chapterDetail.js?v=1',
        'Pictab': 'modules/version/Pictab.js?v=1',
        'newVote': 'modules/vote/0.2.0/vote.js?v=1',
        'teacherList': 'modules/exam/0.2.0/teacherList.js?v=2',
        'studentExamList': 'modules/exam/0.2.0/studentExamList.js?v=2',
        'app': 'modules/appManage/0.1.0/app.js?v=1',
        'phoneApp': 'modules/appManage/0.1.0/phoneApp.js?v=1',
        'bookSelect': 'modules/version/0.1.0/bookSelect.js?v=1',
        'newjiaoan': 'modules/newjiao/0.1.0/newjiaoan.js',
        'jiaoanlist': 'modules/newjiao/0.1.0/jiaoanlist.js',
        'jiaoanjiti': 'modules/newjiao/0.1.0/jiaoanjiti.js',
        'kjiao': 'modules/newjiao/0.1.0/kjiao.js',
        'planFolder': 'modules/newjiao/0.1.0/planFolder.js',
        'folderDetail': 'modules/newjiao/0.1.0/folderDetail.js',
        'newPPLesson': 'modules/newjiao/0.1.0/newPPLesson.js',
        'interact': 'modules/weiSchool/0.1.0/interact.js?v=1',
        'hometown': 'modules/weiSchool/0.1.0/hometown.js?v=1',
        'authority': 'modules/weiSchool/0.1.0/authority.js?v=1',
        'bookSelect': 'modules/version/0.1.0/bookSelect.js?v=1',
        'homework': 'modules/homework/0.1.0/homework.js?v=1',
        'homeworkSign': 'modules/homework/0.1.0/homeworkSign.js?v=1',
        'attendence': 'modules/electronicClassCard/0.1.0/attendance.js?v=1',
        'star': 'modules/electronicClassCard/0.1.0/star.js?v=1',
        'dzduty': 'modules/electronicClassCard/0.1.0/dzduty.js?v=1',
        'Mrecord': 'modules/learncenter/0.2.0/Mrecord.js?v=2',
        'media': 'modules/electronicClassCard/0.1.0/media.js?v=1',

        'oaSalaryNext': 'modules/oaSalary/oaSalaryNext.js?v=1',
        'oaSalaryReward': 'modules/oaSalary/oaSalaryReward.js?v=1',
        'oaWages': 'modules/oaSalary/oaWages.js?v=1',
        'jurisdiction': 'modules/oaSalary/jurisdiction.js?v=1',
        'oaWagesUse': 'modules/oaSalary/oaWagesUse.js?v=1',

        'sui': 'modules/oaRepair/sui.min.js?v=1',
        'myRepair': 'modules/oaRepair/myRepair.js?v=1',
        'repairManage': 'modules/oaRepair/repairManage.js?v=1',
        'repairCount': 'modules/oaRepair/repairCount.js?v=1',
        'repairSet': 'modules/oaRepair/repairSet.js',

        'oaStudentDoor': 'modules/oadoor/studentDoor.js?v=1',
        'oaOuterDoor': 'modules/oadoor/outerDoor.js?v=1',

        'dznotice': 'modules/electronicClassCard/0.1.0/notice.js?v=1',
        'schIntroduce': 'modules/electronicClassCard/0.1.0/schIntroduce.js?v=1',
        'schHonor': 'modules/electronicClassCard/0.1.0/schHonor.js?v=1',
        'clsHonor': 'modules/electronicClassCard/0.1.0/clsHonor.js?v=1',
        'classIntroduce': 'modules/electronicClassCard/0.1.0/classIntroduce.js?v=1',
        'dzclassManage': 'modules/electronicClassCard/0.1.0/dzclassManage.js?v=1',
        'moredurank': 'modules/electronicClassCard/0.1.0/moredurank.js?v=1',
        'dzschMien': 'modules/electronicClassCard/0.1.0/dzschMien.js?v=1',
        'dzschGovern': 'modules/electronicClassCard/0.1.0/dzschGovern.js?v=1',
        'dzschWork': 'modules/electronicClassCard/0.1.0/dzschWork.js?v=1',
        'elecVote': 'modules/electronicClassCard/0.1.0/vote.js?v=1',
        'questionnaire': 'modules/electronicClassCard/0.1.0/questionnaire.js?v=1',
        'activity': 'modules/electronicClassCard/0.1.0/activity.js?v=1',
        'elecCheck': 'modules/electronicClassCard/0.1.0/elecCheck.js?v=1',
        'dzclsMien': 'modules/electronicClassCard/0.1.0/dzclsMien.js?v=1',
        'syllabus3': 'modules/electronicClassCard/0.1.0/syllabus3.js?v=1',
        'syllabus2': 'modules/electronicClassCard/0.1.0/syllabus2.js?v=1',
        'dzevaluate': 'modules/electronicClassCard/0.1.0/dzevaluate.js?v=1',
        'dutyEvaluate': 'modules/electronicClassCard/0.1.0/dutyEvaluate.js?v=1',
        'personal': 'modules/electronicClassCard/0.1.0/personal.js?v=1',
        'award': 'modules/electronicClassCard/0.1.0/award.js?v=1',
        'sign': 'modules/electronicClassCard/0.1.0/sign.js?v=1',
        'nhomework': 'modules/yan/nhomework.js?v=1',
        'dnhomework': 'modules/yan/dnhomework.js?v=1',
        'stunhomework': 'modules/yan/stunhomework.js?v=1',
        'Mclassroom': 'modules/Interactive/Mclassroom.js?v=1',
        'Interactivereso': 'modules/Interactive/Interactivereso.js?v=1',
        'Classroomprev': 'modules/Interactive/Classroomprev.js?v=1',
        'docflowindex': 'modules/docflow/docflowindex.js?v=1',
        'docflowedit': 'modules/docflow/docflowedit.js?v=1',
        'docflowdetail': 'modules/docflow/docflowdetail.js?v=1',
        'docflowmydetail': 'modules/docflow/docflowmydetail.js?v=1',
        'docflowread': 'modules/docflow/docflowread.js?v=1',
        'docflowverify': 'modules/docflow/docflowverify.js?v=1',
        'docflowtoedit': 'modules/docflow/docflowtoedit.js?v=1',
        'equipment': 'modules/equipment/equipment.js?v=1',
        'equipmentDeng': 'modules/equipment/equipmentDeng.js?v=1',
        'myuse': 'modules/equipment/myuse.js?v=1',
        'mManagement': 'modules/comprehensiveQuality/0.1.0/mManagement.js?v=1',
        'sDetails': 'modules/comprehensiveQuality/0.1.0/sDetails.js?v=1',
        'tEvaluation': 'modules/comprehensiveQuality/0.1.0/tEvaluation.js?v=1',
        'addEvaluation': 'modules/comprehensiveQuality/0.1.0/addEvaluation.js?v=1',
        'mDetails': 'modules/comprehensiveQuality/0.1.0/mDetails.js?v=1',
        'cDetails': 'modules/comprehensiveQuality/0.1.0/cDetails.js?v=1',
        'tDetails': 'modules/comprehensiveQuality/0.1.0/tDetails.js?v=1',
        'dDetails': 'modules/comprehensiveQuality/0.1.0/dDetails.js?v=1',
        'Restitution': 'modules/equipment/Restitution.js?v=1',
        'anal': 'modules/equipment/anal.js?v=1',
        'Set': 'modules/equipment/Set.js?v=1',
        'evalIntro': 'modules/evalspecify/0.1.0/evalIntro.js?v=1',
        'evalApply': 'modules/evalspecify/0.1.0/evalApply.js?v=1',
        'evalManage': 'modules/evalspecify/0.1.0/evalManage.js?v=1',
        'evalAdd': 'modules/evalspecify/0.1.0/evalAdd.js?v=1',
        'evalSetting': 'modules/evalspecify/0.1.0/evalSetting.js?v=1',
        'staffinstruction': 'modules/staffevaluation/0.1.0/evaluationinstruction.js?v=1',
        'staffevalset': 'modules/staffevaluation/0.1.0/staffevalset.js?v=1',
        'staffevaladd3': 'modules/staffevaluation/0.1.0/staffevaladd3.js?v=1',
        'staffevalmyeval': 'modules/staffevaluation/0.1.0/staffevalmyeval.js?v=1',
        'staffevaladd2': 'modules/staffevaluation/0.1.0/staffevaladd2.js?v=1',
        'staffevalinformation': 'modules/staffevaluation/0.1.0/staffevalinformation.js?v=1',
        'staffpingjia': 'modules/staffevaluation/0.1.0/staffpingjia.js?v=1',
        'staffevalamanager': 'modules/staffevaluation/0.1.0/staffevalamanager.js?v=1',
        'staffmyevalresult': 'modules/staffevaluation/0.1.0/staffmyevalresult.js?v=1',
        'staffevalprocess': 'modules/staffevaluation/0.1.0/staffevalprocess.js?v=1',
        'evaluationscore': 'modules/staffevaluation/0.1.0/evaluationscore.js?v=1',
        'staffshehe': 'modules/staffevaluation/0.1.0/staffshehe.js?v=1',
        'staffdetail': 'modules/staffevaluation/0.1.0/staffdetail.js?v=1',
        'fixedTable':'modules/teaEvaluation/0.1.0/fixed-table.js?v=1',
        'controlMge':'modules/teaEvaluation/0.1.0/controlMge.js?v=1',
        'teaEvalSetting':'modules/teaEvaluation/0.1.0/teaEvalSetting.js?v=1',
        'selfEval':'modules/teaEvaluation/0.1.0/selfEval.js?v=2',
        'mutualEval':'modules/teaEvaluation/0.1.0/mutualEval.js?v=1',
        'mutualEvalV2':'modules/teaEvaluation/0.1.0/mutualEvalV2.js?v=3',
        'basicEval':'modules/teaEvaluation/0.1.0/basicEval.js?v=1',
        'basicEvalV2':'modules/teaEvaluation/0.1.0/basicEvalV2.js?v=3',
        'evalResult':'modules/teaEvaluation/0.1.0/evalResult.js?v=1',
        'evaluationsee':'modules/staffevaluation/0.1.0/evaluationsee.js?v=1',
        'dzpublicity':'modules/electronicClassCard/0.1.0/dzpublicity.js?v=1',

        'systemSetting':'modules/majorAbilityEva/0.1.0/systemSetting.js?v=1',
        'maeTeacherList':'modules/majorAbilityEva/0.1.0/teacherList.js?v=1',
        'evaSysMge':'modules/majorAbilityEva/0.1.0/evaSysMge.js?v=1',
        'evaSysEdit':'modules/majorAbilityEva/0.1.0/evaSysEdit.js?v=1',
        'evaSysView':'modules/majorAbilityEva/0.1.0/evaSysView.js?v=1',
        'checkTableList':'modules/majorAbilityEva/0.1.0/checkTableList.js?v=1',
        'checkDataInput':'modules/majorAbilityEva/0.1.0/checkDataInput.js?v=1',
        'abilityEvaResult':'modules/majorAbilityEva/0.1.0/abilityEvaResult.js',
        'abilityEvaChildResult':'modules/majorAbilityEva/0.1.0/abilityEvaChildResult.js',
        'myEvaResult':'modules/majorAbilityEva/0.1.0/myEvaResult.js?v=1',
        'teacherIndex' : 'modules/majorAbilityEva/0.1.0/teacherIndex.js',


        'myLesson' : 'modules/interactLesson/myLesson.js',
        'lessonView' : 'modules/interactLesson/lessonView.js',
        'teaLesson' : 'modules/interactLesson/teaLesson.js',
        
        'examinationset':'modules/jinyuanananly/examinationset.js',
        'templatemanage':'modules/jinyuanananly/templatemanage.js',
        'createtemplate':'modules/jinyuanananly/createtemplate.js',
        'edittemplate':'modules/jinyuanananly/edittemplate.js',
        'analyzeindex':'modules/jinyuanananly/analyzeindex.js',
        'personalindex':'modules/jinyuanananly/personalindex.js',
        'teapersonalindex':'modules/jinyuanananly/teapersonalindex.js',
        'historyexcel':'modules/jinyuanananly/historyexcel.js',
        'auditing':'modules/functionClass/auditing.js',
        'stuAttendance': 'modules/stuAttendance/0.1.0/stuAttendance.js?v=1',
        // 解决ie兼容性问题
        'ieSolution' : "modules/ieFunc/ieSolution.js",
        'reserveclassroom': 'modules/evaluation/0.1.0/reserveclassroom.js?v=1',
        'ieSolution' : "modules/ieFunc/ieSolution.js",
        'clsromReserve':"modules/functionClass/clsromReserve.js",
        'myOrder':"modules/functionClass/myOrder.js",
        'Fset':"modules/functionClass/Fset.js",
        'myReserve': 'modules/evaluation/0.1.0/myReserve.js?v=1',
        'teapersonal':'modules/personal/0.1.0/teapersonal.js?v=1',
        'tearefine':'modules/teaEvaluation/0.1.0/refine.js?v=1',
        't33':'modules/t33/0.1.0/t33.js?v=1',
        'fenban':'modules/t33/0.1.0/fenban.js?v=1',
        'fenbancheck':'modules/t33/0.1.0/fenbancheck.js?v=1',
        'stupersonal':'modules/personal/0.1.0/stupersonal.js?v=1',
        'fenbancheckpage':'modules/t33/0.1.0/fenbancheckpage.js?v=1',
        'fenbanzuhe':'modules/t33/0.1.0/fenbanzuhe.js?v=1',

        'evaSysMgr':'modules/electiveGuidance/0.1.0/evaSysMgr.js?v=1',
        'evaSysStu':'modules/electiveGuidance/0.1.0/evaSysStu.js?v=1',
        'courseReport':'modules/electiveGuidance/0.1.0/courseReport.js?v=1',
        'hollandReport':'modules/electiveGuidance/0.1.0/hollandReport.js?v=1',
        'stuCourseTest':'modules/electiveGuidance/0.1.0/stuCourseTest.js?v=1',
        'stuCourseReport':'modules/electiveGuidance/0.1.0/stuCourseReport.js?v=1',
        'stuHollandTest':'modules/electiveGuidance/0.1.0/stuHollandTest.js?v=1',
        'stuHollandReport':'modules/electiveGuidance/0.1.0/stuHollandReport.js?v=1',
        'finishProgress':'modules/electiveGuidance/0.1.0/finishProgress.js?v=1',

        'qualitylist':"modules/electiveGuidance/qualitylist.js?v=1",
        'qualityset':"modules/electiveGuidance/qualityset.js?v=1",
        'guidereport' : "modules/electiveGuidance/guidereport.js",
        'qualityprevious':"modules/electiveGuidance/qualityprevious.js?v=1",
        'qualityinfo':"modules/electiveGuidance/qualityinfo.js?v=1",
        'qualitystuinfo':"modules/electiveGuidance/qualitystuinfo.js?v=1",
        'guidereport-stu' : 'modules/electiveGuidance/guidereport-stu.js',
        'mComprehensiv':'modules/comprehensiveQuality/0.1.0/mComprehensiv.js?v=1',
        'mHistory':'modules/comprehensiveQuality/0.1.0/mHistory.js?v=1',
        'tUpdate':'modules/comprehensiveQuality/0.1.0/tUpdate.js?v=1',
        'tTab':'modules/comprehensiveQuality/0.1.0/tTab.js?v=1',
        'stuCQSetting' : 'modules/comprehensiveQuality/0.1.0/stuCQSetting.js?v=1',
        'autocomplete':'modules/comprehensiveQuality/0.1.0/jquery-ui.js?v=1',
        'gConfirm':'modules/comprehensiveQuality/0.1.0/gConfirm.js?v=1',
        'record':'modules/comprehensiveQuality/0.1.0/record.js?v=1',
        'mStudent':'modules/comprehensiveQuality/0.1.0/mStudent.js?v=1',
        'mMaterial':'modules/comprehensiveQuality/0.1.0/mMaterial.js?v=1',
        'mMaterial-prev':'modules/comprehensiveQuality/0.1.0/mMaterial-prev.js?v=1',
        'schoolSelectLessonSet':'modules/new33/0.1.0/schoolSelectLessonSet.js?v=1',
        'baseClassroom':'modules/new33/0.1.0/baseClassroom.js?v=1',
        'classTime':'modules/new33/0.1.0/classTime.js?v=1',
        'pkTable':'modules/new33/0.1.0/pkTable.js?v=1',
        'pkTableTiaoke':'modules/new33/0.1.0/pkTableTiaoke.js?v=1',
        'pkTableAll':'modules/new33/0.1.0/pkTableAll.js?v=1',
        'excCourse':'modules/new33/0.1.0/excCourse.js?v=1',
        'excCourseLog':'modules/new33/0.1.0/excCourseLog.js?v=1',
        'baseTable':'modules/new33/0.1.0/baseTable.js?v=1',
        'baseWeek':'modules/new33/0.1.0/baseWeek.js?v=1',
        'baseTeacher':'modules/new33/0.1.0/baseTeacher.js?v=1',
        'baseAffair':'modules/new33/0.1.0/baseAffair.js?v=1',
        'stuGrade':'modules/new33/0.1.0/stuGrade.js?v=1',
        'stuAdmini':'modules/new33/0.1.0/stuAdmini.js?v=1',
        'stuselect':'modules/new33/0.1.0/stuselect.js?v=1',
        'selectResult':'modules/new33/0.1.0/selectResult.js?v=1',
        'selectClassresult':'modules/new33/0.1.0/selectClassresult.js?v=1',
        'teaCLassTime':'modules/new33/0.1.0/teaCLassTime.js?v=1',
        'pTeaClassTime':'modules/new33/0.1.0/pTeaClassTime.js?v=1',
        'pStuClassTime':'modules/new33/0.1.0/pStuClassTime.js?v=1',
        'pStuClassTimeStu':'modules/new33/0.1.0/pStuClassTimeStu.js?v=1',
        'jSubCLassTime':'modules/new33/0.1.0/jSubCLassTime.js?v=1',
        'classTable':'modules/new33/0.1.0/classTable.js?v=1',
        'allTable':'modules/new33/0.1.0/allTable.js?v=1',
        'set':'modules/new33/0.1.0/set.js?v=1',
        'afreshClass':'modules/new33/0.1.0/afreshClass.js?v=1',
        'fenbanInfoSet':'modules/new33/0.1.0/fenbanInfoSet.js?v=1',
        'danShuangZhou':'modules/new33/0.1.0/danShuangZhou.js?v=1',
        'placementSet':'modules/new33/0.1.0/placementSet.js?v=1',
        'conflict':'modules/new33/0.1.0/conflict.js?v=1',
        'stuSign':'modules/new33/0.1.0/stuSign.js?v=1',
        'stuRelation':'modules/new33/0.1.0/stuRelation.js?v=1',
        'selectResultCharts':'modules/new33/0.1.0/selectResultCharts.js?v=1',
        'zhuanXiang':'modules/new33/0.1.0/zhuanXiang.js?v=1',
        'zixiclass':'modules/new33/0.1.0/zixiclass.js?v=1',
        'paikereport':'modules/new33/0.1.0/paikereport.js?v=1',
        'jxbRelation':'modules/new33/0.1.0/jxbRelation.js?v=1',
        'baseGuiZe':'modules/new33/0.1.0/baseGuiZe.js?v=1',
        'paiKeZuHe':'modules/new33/0.1.0/paiKeZuHe.js?v=1',
        'autoTimeCombKeBiao':'modules/new33/0.1.0/autoTimeCombKeBiao.js?v=1',
        'jxbcombine':'modules/new33/0.1.0/jxbcombine.js?v=1',
        'MyTimetable':'modules/new33/0.1.0/MyTimetable.js?v=1',
        'MyClass':'modules/new33/0.1.0/MyClass.js?v=1',
        'MyClassTi':'modules/new33/0.1.0/MyClassTi.js?v=1',
        'daike':'modules/new33/0.1.0/daike.js?v=1',
        'selectProgress':'modules/new33/0.1.0/selectProgress.js?v=1',
        'teaDemand':'modules/new33/0.1.0/teaDemand.js?v=1',
        'auditDemand':'modules/new33/0.1.0/auditDemand.js?v=1',
        'subTable':'modules/new33/0.1.0/subTable.js?v=1',
        'compared':'modules/new33/0.1.0/compared.js?v=1',
        'fselect':'/static/js/fselect/fselect.js?v=1',
        'dbtkClass':'modules/new33/0.1.0/dbtkClass.js?v=1',
        'zjtkClass':'modules/new33/0.1.0/zjtkClass.js?v=1',
        'jxbTimeCombine':'modules/new33/0.1.0/jxbTimeCombine.js?v=1',
        'jxbAutoTimeCombine':'modules/new33/0.1.0/jxbAutoTimeCombine.js?v=1',
        'jxClass':'modules/new33/0.1.0/jxClass.js?v=1',
        'pkRuleSet':'modules/new33/0.1.0/pkRuleSet.js?v=1',
        'dzbpClassKeBiao':'modules/dzbp/dzbpClassKeBiao.js',
        'dzbpClassKeBiaoTwo':'modules/dzbp/dzbpClassKeBiaoTwo.js',

    },
    preload: [
        Function.prototype.bind ? '' : 'es5-safe',
        this.JSON ? '' : 'json',
        'jquery',
        'doT'
    ]
});